name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Correctly using the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Upgraded to v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Zip codebase
        run: |
          mkdir release
          cp -r ./dist/* ./release/  
          cd release
          zip -r ../easyBot.zip .  
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1  # Version can stay at v1, but ensure it's working
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: v${{ github.sha }}  # Using `github.sha` for more stable versioning
          release_name: Release v${{ github.sha }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1  # Version can stay at v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./easyBot.zip
          asset_name: easyBot.zip
          asset_content_type: application/zip
